CREATE TABLE PIECE ( NOP NUMBER(3), DESIGNATION VARCHAR(20), COULEUR VARCHAR(15), POIDS NUMBER(5,2) ) ; 
INSERT INTO PIECE (NOP, DESIGNATION, COULEUR, POIDS) VALUES (1, 'Piece1', 'Argent', 1);
INSERT INTO PIECE (NOP, DESIGNATION, COULEUR, POIDS) VALUES (2, ' Piece2', 'Bronze', 2);
INSERT INTO PIECE (NOP, DESIGNATION, COULEUR, POIDS) VALUES (3, ' Piece3', 'Noir', 3);

CREATE TABLE SERVICE (NOS NUMBER(3), INTITULE VARCHAR(20), LOCALISATION VARCHAR(30) ) ; 
INSERT INTO SERVICE (NOS, INTITULE, LOCALISATION) VALUES (101, 'Service Informatique', 'Bâtiment A');
INSERT INTO SERVICE (NOS, INTITULE, LOCALISATION) VALUES (102, 'Service Ressources Humaines', 'Bâtiment B');
INSERT INTO SERVICE (NOS, INTITULE, LOCALISATION) VALUES (103, 'Service Comptabilité', 'Bâtiment C');

CREATE TABLE ORDRE ( NOP NUMBER(3), NOS NUMBER(3), QUANTITE NUMBER(3) ) ;
INSERT INTO ORDRE (NOP, NOS, QUANTITE) VALUES (1, 101, 100);
INSERT INTO ORDRE (NOP, NOS, QUANTITE) VALUES (2, 102, 50);
INSERT INTO ORDRE (NOP, NOS, QUANTITE) VALUES (3, 103, 200);

CREATE TABLE NOMENCLATURE (NOPA NUMBER(3), NOPC NUMBER(3), QUANTITE NUMBER(3) ) ;
INSERT INTO NOMENCLATURE (NOPA, NOPC, QUANTITE) VALUES (1, 101, 10);
INSERT INTO NOMENCLATURE (NOPA, NOPC, QUANTITE) VALUES (2, 102, 5);
INSERT INTO NOMENCLATURE (NOPA, NOPC, QUANTITE) VALUES (3, 101, 20);

/*
INSERT INTO PIECE (NOP, DESIGNATION, COULEUR, POIDS) VALUES (1, 'Piece1', 'Argent', 1);
INSERT INTO PIECE (NOP, DESIGNATION, COULEUR, POIDS) VALUES (1, ' Piece2', 'Bronze', 2);
INSERT INTO SERVICE (NOS, INTITULE, LOCALISATION) VALUES (101, 'Service Informatique', 'Bâtiment A');
INSERT INTO SERVICE (NOS, INTITULE, LOCALISATION) VALUES (101, 'Service Ressources Humaines', 'Bâtiment B');
INSERT INTO ORDRE (NOP, NOS, QUANTITE) VALUES (101, 201, 5);
INSERT INTO ORDRE (NOP, NOS, QUANTITE) VALUES (102, 201, 3);
INSERT INTO NOMENCLATURE (NOPA, NOPC, QUANTITE) VALUES (101, 102, 5);
INSERT INTO NOMENCLATURE (NOPA, NOPC, QUANTITE) VALUES (102, 103, 3);
*/
ALTER TABLE PIECE ADD CONSTRAINT PK_PIECE PRIMARY KEY (NOP);
ALTER TABLE SERVICE ADD CONSTRAINT PK_SERVICE PRIMARY KEY (NOS);
ALTER TABLE ORDRE ADD CONSTRAINT PK_ORDRE PRIMARY KEY (NOP, NOS);
ALTER TABLE NOMENCLATURE ADD CONSTRAINT PK_NOMENCLATURE PRIMARY KEY (NOPA, NOPC);
ALTER TABLE ORDRE ADD CONSTRAINT FK_ORDRE_SERVICE FOREIGN KEY (NOS) REFERENCES SERVICE(NOS);
ALTER TABLE ORDRE ADD CONSTRAINT FK_ORDRE1_SERVICE FOREIGN KEY (NOP) REFERENCES PIECE (NOP) ;
ALTER TABLE NOMENCLATURE ADD CONSTRAINT FK_NOMENCLATURE_PIECE FOREIGN KEY (NOPA) REFERENCES PIECE(NOP);
ALTER TABLE NOMENCLATURE ADD CONSTRAINT FK_NOMENCLATURE2_PIECE FOREIGN KEY (NOPC) REFERENCES PIECE (NOP) ;

DELETE FROM PIECE WHERE NOP = 1;
DELETE FROM SERVICE WHERE NOS = 101;
UPDATE ORDRE SET NOS = 101 WHERE NOS = 201;
ALTER TABLE PIECE ADD CONSTRAINT CK_COULEUR CHECK (COULEUR IN ('ROUGE', 'VERTE', 'BLEUE', 'JAUNE'));
ALTER TABLE PIECE MODIFY (DESIGNATION VARCHAR(30));
ALTER TABLE SERVICE MODIFY (INTITULE VARCHAR(30));

ALTER TABLE SERVICE ADD (DIRECTEUR VARCHAR(50));
ALTER TABLE SERVICE DROP COLUMN LOCALISATION;
ALTER TABLE PIECE DROP PRIMARY KEY ;
ALTER TABLE PIECE DROP CONSTRAINT CK_COULEUR;
DROP TABLE NOMENCLATURE;
DROP TABLE ORDRE CASCADE CONSTRAINTS ; 
SELECT * FROM PIECE ; 
SELECT * FROM SERVICE ;

/*
RECAPITULATIF

SELECT * FROM NOMENCLATURE ;
NOMENCLATURE
NOPA	NOPC	QUANTITE
1	101	10
1	102	5
2	101	20

SELECT * FROM ORDRE ;
ORDRE
NOP	NOS	QUANTITE
1	101	100
2	102	50
3	103	200

SELECT * FROM PIECE ; 
PIECE
NOP	DESIGNATION	COULEUR		POIDS
1	Piece1		Argent		1
2	Piece2		Bronze		2
3	Piece3		Noir		3

SELECT * FROM SERVICE ;
SERVICE
NOS	INTITULE			LOCALISATION
101	Service Informatique		Bâtiment A
102	Service Ressources Humaines	Bâtiment B
103	Service Comptabilité		Bâtiment C

*/